service: youtubeStudySpace

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  timeout: 30
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ${self:custom.regions.${self:provider.stage}}
  apiGateway:
    apiKeys:
      - youtube-study-space:
        - name: youtube-study-space-api-key
          value: ${env:YOUTUBE_STUDY_SPACE_API_KEY}
    

custom:
  defaultStage: dev
  profiles:
    dev: soraride
    prod: serverless-prod
  regions:
    dev: us-east-1
    prod: ap-northeast-1

functions:
  roomsState:
    handler: rooms_state
    name: rooms_state
    events:
      - http:
          path: /rooms_state
          method: get
          cors: true
          private: true
      - cloudwatchLog:
          logGroup: '/aws/lambda/rooms_state'



