AWSTemplateFormatVersion: 2010-09-09
Description: "Lambda and Api gateway settings"



Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "" # TODO
      RoleName: "" # TODO


  Api:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !FindInMap [Constants, Api, ApiName]
  Resource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref Api
      ParentId: !GetAtt Api.RootResourceId
      PathPart:
  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !FindInMap [Constants, FunctionNames, RoomsState]
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
  ResourceMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref Resource
      AuthorizationType: "None"
      HttpMethod: "GET"
      Integration:
        Type: "AWS"
        Uri: !Sub # TODO
    DependsOn: "LambdaPermission"


